# Create a conda env via: 
# conda env create -f environment.yml
# activate idvorkin_jupyter
name: idvorkin_jupyter
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - psutil
  - toolz
  - matplotlib
  - dill
  - seaborn
  - pandas
  - partd
  - bokeh
  - dask
  - plotly
  - arrow
